version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      ORACLE_USER: ${ORACLE_USER}
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      ORACLE_DSN: ${ORACLE_DSN}

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
